- name: Allocate a new elastic IP
  amazon.aws.ec2_eip:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    state: present
  register: eip
  when: allocation_id is undefined

- name: set avarible eip
  set_fact:
    allocation_id: "{{ eip.allocation_id }}"
  when: eip.changed

- name: Save avarible eip
  shell: "{{ item }}"
  with_items:
    - echo "allocation_id:" {{ allocation_id }} >> vars/var.yml
  when: eip.changed

# - name: DEBUG
#   ansible.builtin.debug:
#     msg: "{{ eip }}"
# #   loop: '{{ instance_info.instances }}'
