- name: Allocate a new elastic IP
  amazon.aws.ec2_eip:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    state: present
  register: eip
  when: allocation_id is undefined

- name: set avarible eip
  set_fact:
    allocation_id: "{{ eip.allocation_id | default(allocation_id )}}"
    state: present

- name: Save avarible eip
  lineinfile: >-
    dest="vars/var.yml"
    state=present
    regexp="allocation_id"
    line='allocation_id: {{ allocation_id }}'

# - name: DEBUG
#   ansible.builtin.debug:
#     msg: "{{ eip }}"
# #   loop: '{{ instance_info.instances }}'
