- hosts: localhost
  connection: local
  any_errors_fatal: true
  gather_facts: true
  vars_files:
    - vars/project.yml
    - vars/aws.yml
    - vars/vpc.yml
    - vars/ec2.yml
    - vars/var.yml
  roles:
    - vpc
    - vpc-internet_gateway
    - vpc-subnet
    - vpc-elastic_ip
    - vpc-nat_gateway
    - { role: vpc-route_table, route_table_name: "RT_public", subnet_id: "{{ subnet_public_id }}", instance_value: "{{ gateway_id }}", create_with_internet: true }
    - { role: vpc-route_table, route_table_name: "RT_private", subnet_id: "{{ subnet_private_id }}", instance_value: "{{ nat_gateway_id }}", create_with_internet: true }
    - { role: vpc-security_group, sg_name: "sg_bastion", only_ssh: true }
    - { role: ec2-keypair }
    - { role: ec2-bastion, sg_id: "{{ sg_bastion_id }}", subnet_id: "{{ subnet_public_id }}" }
    - { role: vpc-security_group, sg_name: "sg_server_web", port22_cidr_block: "{{ bastion_private_ip }}/24", accept_http: true }
    - { role: ec2, sg_id: "{{ sg_server_web_id }}", subnet_id: "{{ subnet_private_id }}" }
    - config-ansible
    - elb_target_group
    - elb
