- hosts: localhost
  connection: local
  any_errors_fatal: true
  gather_facts: true
  vars_files:
    - vars/project.yml
    - vars/aws.yml
    - vars/vpc.yml
    - vars/ec2.yml
    - vars/var.yml
  roles:
    - vpc
    - vpc-internet_gateway
    - vpc-subnet
    - vpc-elastic_ip
    - vpc-nat_gateway
    - { role: vpc-route_table, route_table_name: "RT_public", subnet_id: "{{ subnet_public_id }}", instance_value: "{{ gateway_id }}", create_with_internet: true }
    - { role: vpc-route_table, route_table_name: "RT_private", subnet_id: "{{ subnet_private_id }}", instance_value: "{{ nat_gateway_id }}", create_with_internet: true }
    - { role: vpc-security_group, sg_name: "sg_local" }
    - { role: ec2-keypair, keypair: "{{ keypair_name }}" }
    - { role: ec2-bastion, keypair: "{{ keypair_name }}", sg_id: "{{ sg_local_id }}", subnet_id: "{{ subnet_public_id }}" }
    - { role: vpc-security_group, sg_name: "sg_bastion", port22_cidr_block: "{{ bastion_private_ip }}/24" }
    - { role: ec2, keypair: "{{ keypair_name }}", sg_id: "{{ sg_bastion_id }}", subnet_id: "{{ subnet_publish_id }}" }
    - { role: config-ansible, key: "{{ keypair_name }}" }
    - elb_target_group
    - elb
    # - { role: config-ansible, key: "{{ keypair_name }}" }
