- hosts: app-{{ project_evironment }}
  any_errors_fatal: true
  gather_facts: true
  vars_files:
    - vars/project.yml
    - vars/aws.yml
    - vars/vpc.yml
    - vars/ec2.yml
  roles:
    - add-user
