- name: Create VPC Subnet public {{ project_evironment }}
  ec2_vpc_subnet:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    az: "{{ zone }}"      # az is the availability zone
    state: present
    cidr: "{{ subnet_cidr_publish_block }}"
    # enable public ip
    map_public: yes
    resource_tags:
      Name: "{{ subnet_public }}"
  register: subnet_public_result

- name: set avarible subnet_public_id
  set_fact:
    subnet_public_id: "{{ subnet_public_result.subnet.id }}"
    state: present

- name: Save avarible subnet_public_id
  lineinfile: >-
    dest="vars/var.yml"
    state=present
    regexp="subnet_public_id:"
    line='subnet_public_id: {{ subnet_public_id }}'

- name: Create VPC Subnet private {{ project_evironment }}
  ec2_vpc_subnet:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    az: "{{ zone }}"      # az is the availability zone
    state: present
    cidr: "{{ subnet_cidr_private_block }}"
    # enable public ip
    resource_tags:
      Name: "{{ subnet_private }}"
  register: subnet_private_result

- name: set avarible subnet_private_id
  set_fact:
    subnet_private_id: "{{ subnet_private_result.subnet.id }}"
    state: present

- name: Save avarible subnet_private_id
  lineinfile: >-
    dest="vars/var.yml"
    state=present
    regexp="subnet_private_id:"
    line='subnet_private_id: {{ subnet_private_id }}'
