- name: Create new nat gateway
  amazon.aws.ec2_vpc_nat_gateway:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    state: present
    subnet_id: "{{ subnet_public_ids[0] }}"
    allocation_id: "{{ allocation_id }}"
    wait: true
    if_exist_do_not_create: true
  register: nat_gateway

- name: set avarible nat_gateway
  set_fact:
    ngw_id: "{{ nat_gateway.nat_gateway_id }}"
    state: present

- name: Save avarible nat_gateway_id
  lineinfile: >-
    dest="vars/var.yml"
    state=present
    regexp="ngw_id:"
    line='ngw_id: {{ ngw_id }}'
