- name: Get instance bastion
  amazon.aws.ec2_instance_info:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    instance_ids:
      - "{{ bastion_id }}"
  register: instance_info
- name: write file config ansible
  shell: "{{ item }}"
  with_items:
    - bash -ilc "echo -e 'Host bastion-{{ app_evironment }} \n\tUser ec2-user \n\tHostName {{ instance_info.instances[0].public_ip_address }} \n\tIdentitiesOnly yes \n\tIdentityFile {{ ssh_private_key }} \n' > ssh_config"
    - bash -ilc "echo -e 'Host bastion-{{ app_evironment }}-su \n\tUser ec2-user \n\tHostName {{ instance_info.instances[0].public_ip_address }} \n\tIdentitiesOnly yes \n\tIdentityFile ssh_keys/{{ keypair_name }} \n' >> ssh_config"
- name: write file config .ini
  shell: bash -ilc "echo -e '[bastion]' > {{ app_evironment }}.ini"

- name: write file config .ini
  shell: bash -ilc "echo -e 'bastion-{{ app_evironment }}' >> {{ app_evironment }}.ini"
  loop: '{{ instance_info.instances }}'

- name: write file config .ini
  shell: bash -ilc "echo -e '[bastion-su]' >> {{ app_evironment }}.ini"

- name: write file config .ini
  shell: bash -ilc "echo -e 'bastion-{{ app_evironment }}-su' >> {{ app_evironment }}.ini"
  loop: '{{ instance_info.instances }}'

- name: Get all instance server info
  amazon.aws.ec2_instance_info:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    instance_ids: "{{ ec2_ids }}"
  register: instance_info

- name: write file config ssh_config
  shell: bash -ilc "echo -e 'Host {{ item.tags.Name }}-su \n\tUser ec2-user \n\tHostName {{ item.private_ip_address }} \n\tIdentitiesOnly yes \n\tIdentityFile ssh_keys/{{ keypair_name }} \n\tProxyJump bastion-{{ app_evironment }}-su \n' >> ssh_config"
  loop: '{{ instance_info.instances }}'

- name: write file config ssh_config
  shell: bash -ilc "echo -e 'Host {{ item.tags.Name }} \n\tUser {{ user_deploy }} \n\tHostName {{ item.private_ip_address }} \n\tIdentitiesOnly yes \n\tIdentityFile {{ ssh_private_key }} \n\tProxyJump bastion-{{ app_evironment }} \n' >> ssh_config"
  loop: '{{ instance_info.instances }}'

- name: write file config .ini
  shell: bash -ilc "echo -e '[app-su]' >> {{ app_evironment }}.ini"

- name: write file config .ini
  shell: bash -ilc "echo -e '{{ item.tags.Name }}-su' >> {{ app_evironment }}.ini"
  loop: '{{ instance_info.instances }}'

- name: write file config .ini
  shell: bash -ilc "echo -e '[app]' >> {{ app_evironment }}.ini"

- name: write file config .ini
  shell: bash -ilc "echo -e '{{ item.tags.Name }}' >> {{ app_evironment }}.ini"
  loop: '{{ instance_info.instances }}'

- name: write file config file .ini
  shell: bash -ilc "echo -e '[all:vars]\nstage=app' >> {{ app_evironment }}.ini"
