- name: Create VPC over AWS Cloud {{ project_evironment }}
  ec2_vpc_net:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr_block }}"
    region: "{{ region }}"
    dns_support: yes
    dns_hostnames: yes
    tenancy: default
    state: present
  register: ec2_vpc_net_result

- name: Save avarible vpc_ip
  set_fact:
    vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"

- name: Save avarible vpc_ip
  shell: echo "vpc_id:" {{ vpc_id }} > vars/var.yml
