- name: Create VPC over AWS Cloud {{ project_evironment }}
  ec2_vpc_net:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr_block }}"
    dns_support: yes
    dns_hostnames: yes
    tenancy: default
    state: present
  register: ec2_vpc_net_result

- name: set avarible vpc_ip
  set_fact:
    vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"
    state: present

- name: Save avarible vpc_ip
  lineinfile: >-
    dest="vars/var.yml"
    state=present
    regexp="vpc_id"
    line='vpc_id: {{ vpc_id }}'
