---
- name: Increase Max of File Descriptors
  lineinfile:
    dest: /etc/security/limits.conf
    state: present
    regexp: "{{item.regexp}}"
    line: "{{ item.line }}"
    backrefs: no
    backup: yes
  with_items:
    - regexp: root soft nofile 65536
      line: root soft nofile 65536
    - regexp: root hard nofile 65536
      line: root hard nofile 65536
    - regexp: '\* soft nofile 65536'
      line: '* soft nofile 65536'
    - regexp: '\* hard nofile 65536'
      line: '* hard nofile 65536'
