- name: add user deploy {{ user_deploy }}
  ansible.builtin.user:
    name: "{{ user_deploy }}"
    state: present

- name: add sudoers for {{ user_deploy }}
  become: true
  lineinfile: >-
     dest="/etc/sudoers"
     state=present
     regexp="{{ item.match }}"
     line="{{ item.line }}"
  with_items:
    - { match: "{{ user_deploy }}", line: '{{ user_deploy }} ALL=(ALL) NOPASSWD: /sbin/service' }


# - name: DEBUG
#   ansible.builtin.debug:
#     msg: "{{ lookup('file', lookup('env','HOME') + '/.ssh/{{ ssh_key }}.pub') }}"
# #   loop: '{{ instance_info.instances }}'
