- name:  "Provisioning ec2 instance {{ project_evironment }}"
  ec2_instance:
    image_id: "{{ image_id }}"
    instance_type: "{{ instance_type }}"
    region: "{{ region }}"
    key_name: "{{ key }}"
    wait: yes
    count: 1
    state: present
    vpc_subnet_id: "{{ subnet_private_result.subnet.id }}"
    network:
      assign_public_ip: false
    security_group: "{{ security_group_results.group_id }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    name: "{{ item }}"
  loop: "{{ OS_Names }}"
  register: ec2_instances

# - name: DEBUG bastion
#   ansible.builtin.debug:
#     msg: "{{ ec2_bastion }}"
# - name: DEBUG bastion
#   ansible.builtin.debug:
#     msg: "{{ ec2_instances }}"

#   loop: '{{ instance_info.instances }}'
